### ISSUE TITLE
[Distribution on modpacks outside of CurseForge]

### ISSUE THREAD

**Issue by aaronliu0130** [Mindoth/bigfish#1]
Do modpack authors have the right to redistribute this mod as an override jar, i.e. in Modrinth modpacks? Alternatively, would you like to release on Modrinth or GitHub?

Additional context: Curseforge does not allow downloading mods from curseforge for modrinth modpacks. So when your mod is not available for download elsewhere, the only option is to redistribute the mod's `.jar` file inside the modpack and move the files to the `mods` directory. Manually moving files like this in a modpack is called overriding.

**Comment by Mindoth** [comment]
I am not familiar with Modrinth, but I generally allow the use of my mods on modpacks outside of CurseForge too. I was under the impression that toggling on the option to allow outside distribution on the project's CurseForge page would enable the mod to be downloaded into modpacks hosted elsewhere. I'll most likely take a look at making this easier in the future then. Until I do this you can distribute the .jar, sure.

**Comment by aaronliu0130** [comment]
Thanks! Also, sorry for somehow forgetting to do the title. Also, Modrinth modpacks count as "modpacks hosted elsewhere".

**Comment by Mindoth** [comment]
This mod has now been uploaded to Modrinth.
