### ISSUE TITLE
cooked eel has no stats

### ISSUE THREAD

**Issue by Aceplante** [Mindoth/bigfish#5]
So I have appleskin to view food stats and noticed the cooked eel didnt have any. It can still be eaten, and gives 3 full bars, but why would this be the case?

Version of Minecraft: 1.18.2
 
Version of Mod: 1.1.1
 
Client or Server: N/a

**Comment by Mindoth** [comment]
Appleskin can't show the foodstats to Cooked Slimy Eel since it always restores a random amount of hunger. This is written in the modpage on Curseforge.

**Comment by Aceplante** [comment]
ah must have missed that apologies
